//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWsShipBuilder.Core.DataUI.UnitTranslations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UnitLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnitLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWsShipBuilder.Core.DataUI.UnitTranslations.UnitLocalization", typeof(UnitLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        public static string Unit_Degree {
            get {
                return ResourceManager.GetString("Unit_Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °/s.
        /// </summary>
        public static string Unit_DegreePerSecond {
            get {
                return ResourceManager.GetString("Unit_DegreePerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dps.
        /// </summary>
        public static string Unit_DPS {
            get {
                return ResourceManager.GetString("Unit_DPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP.
        /// </summary>
        public static string Unit_HP {
            get {
                return ResourceManager.GetString("Unit_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        public static string Unit_KG {
            get {
                return ResourceManager.GetString("Unit_KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km.
        /// </summary>
        public static string Unit_KM {
            get {
                return ResourceManager.GetString("Unit_KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kts.
        /// </summary>
        public static string Unit_Knots {
            get {
                return ResourceManager.GetString("Unit_Knots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Unit_M {
            get {
                return ResourceManager.GetString("Unit_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string Unit_MM {
            get {
                return ResourceManager.GetString("Unit_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string Unit_MPS {
            get {
                return ResourceManager.GetString("Unit_MPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string Unit_PerCent {
            get {
                return ResourceManager.GetString("Unit_PerCent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string Unit_S {
            get {
                return ResourceManager.GetString("Unit_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shots/s.
        /// </summary>
        public static string Unit_ShotsPerSecond {
            get {
                return ResourceManager.GetString("Unit_ShotsPerSecond", resourceCulture);
            }
        }
    }
}
