<Project>
  <PropertyGroup>
    <CommonTargetFramework>net10.0</CommonTargetFramework>
    <DesktopTargetFramework>net10.0-windows</DesktopTargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>$(CommonTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <AnalysisMode>Recommended</AnalysisMode>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
</Project>
