namespace WoWsShipBuilder.Data.Generator.Test.DataElementGeneratorTest;

public partial class DataElementGeneratorTest
{
    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextNoLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial record TestRecord : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ValuesPropertyName = nameof(TestValues))]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial record TestRecord
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.DataElements.FormattedTextDataElement(this.Test, this.TestValues, false, false, false, false));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextValuesLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial record TestRecord : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ValuesPropertyName = nameof(TestValues), ArePropertyNameValuesKeys = true)]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial record TestRecord
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.DataElements.FormattedTextDataElement(this.Test, this.TestValues, false, false, true, false));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextKeyLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial record TestRecord : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ValuesPropertyName = nameof(TestValues), IsValueLocalizationKey = true)]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial record TestRecord
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.DataElements.FormattedTextDataElement(this.Test, this.TestValues, true, false, false, false));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextKeyAndValueLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial record TestRecord : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ValuesPropertyName = nameof(TestValues), IsValueLocalizationKey = true, ArePropertyNameValuesKeys = true)]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial record TestRecord
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.DataElements.FormattedTextDataElement(this.Test, this.TestValues, true, false, true, false));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextValuesAppLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial record TestRecord : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ValuesPropertyName = nameof(TestValues), IsPropertyNameValuesAppLocalization = true)]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial record TestRecord
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.DataElements.FormattedTextDataElement(this.Test, this.TestValues, false, false, false, true));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextKeyAppLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial record TestRecord : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ValuesPropertyName = nameof(TestValues), IsValueAppLocalization = true)]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial record TestRecord
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.DataElements.FormattedTextDataElement(this.Test, this.TestValues, false, true, false, false));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextKeyAndValueAppLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial record TestRecord : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ValuesPropertyName = nameof(TestValues), IsValueAppLocalization = true, IsPropertyNameValuesAppLocalization = true)]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial record TestRecord
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.DataElements.FormattedTextDataElement(this.Test, this.TestValues, false, true, false, true));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }
}
