//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWsShipBuilder.UI.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWsShipBuilder.UI.Translations.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to menu.
        /// </summary>
        public static string MainWindow_BackToMenu {
            get {
                return ResourceManager.GetString("MainWindow_BackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string MainWindow_Range {
            get {
                return ResourceManager.GetString("MainWindow_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate of Fire.
        /// </summary>
        public static string MainWindow_RateOfFire {
            get {
                return ResourceManager.GetString("MainWindow_RateOfFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Build.
        /// </summary>
        public static string MainWindow_ResetBuild {
            get {
                return ResourceManager.GetString("MainWindow_ResetBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Build.
        /// </summary>
        public static string MainWindow_ShareBuild {
            get {
                return ResourceManager.GetString("MainWindow_ShareBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180° Turn Time.
        /// </summary>
        public static string MainWindow_TurnTime {
            get {
                return ResourceManager.GetString("MainWindow_TurnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a build.
        /// </summary>
        public static string StartMenu_LoadBuild {
            get {
                return ResourceManager.GetString("StartMenu_LoadBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new build.
        /// </summary>
        public static string StartMenu_NewBuild {
            get {
                return ResourceManager.GetString("StartMenu_NewBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous builds found.
        /// </summary>
        public static string StartMenu_NoPreviousBuilds {
            get {
                return ResourceManager.GetString("StartMenu_NoPreviousBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings and Info.
        /// </summary>
        public static string StartMenu_Settings {
            get {
                return ResourceManager.GetString("StartMenu_Settings", resourceCulture);
            }
        }
    }
}
