//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWsShipBuilder.UI.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWsShipBuilder.UI.Translations.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Carrier.
        /// </summary>
        public static string AirCarrier {
            get {
                return ResourceManager.GetString("AirCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battleship.
        /// </summary>
        public static string Battleship {
            get {
                return ResourceManager.GetString("Battleship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb.
        /// </summary>
        public static string Bomb {
            get {
                return ResourceManager.GetString("Bomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build saved.
        /// </summary>
        public static string BuildCreationWindow_BuildSaved {
            get {
                return ResourceManager.GetString("BuildCreationWindow_BuildSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the build name. The ship name is automatically included..
        /// </summary>
        public static string BuildCreationWindow_InsertBuildName {
            get {
                return ResourceManager.GetString("BuildCreationWindow_InsertBuildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build string saved on clipboard.
        /// </summary>
        public static string BuildCreationWindow_SavedClipboard {
            get {
                return ResourceManager.GetString("BuildCreationWindow_SavedClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string BuildImport_Import {
            get {
                return ResourceManager.GetString("BuildImport_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import only.
        /// </summary>
        public static string BuildImport_ImportOnly {
            get {
                return ResourceManager.GetString("BuildImport_ImportOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import and save.
        /// </summary>
        public static string BuildImport_ImportSave {
            get {
                return ResourceManager.GetString("BuildImport_ImportSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the build string here.
        /// </summary>
        public static string BuildImport_InsertBuild {
            get {
                return ResourceManager.GetString("BuildImport_InsertBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Build.
        /// </summary>
        public static string BuildImport_Title {
            get {
                return ResourceManager.GetString("BuildImport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Camo Bonuses.
        /// </summary>
        public static string CaptainSkillSelector_Camo {
            get {
                return ResourceManager.GetString("CaptainSkillSelector_Camo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain points :.
        /// </summary>
        public static string CaptainSkillSelector_Points {
            get {
                return ResourceManager.GetString("CaptainSkillSelector_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Talents.
        /// </summary>
        public static string CaptainSkillSelector_Talents {
            get {
                return ResourceManager.GetString("CaptainSkillSelector_Talents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commonwealth.
        /// </summary>
        public static string Commonwealth {
            get {
                return ResourceManager.GetString("Commonwealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruiser.
        /// </summary>
        public static string Cruiser {
            get {
                return ResourceManager.GetString("Cruiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth Charges.
        /// </summary>
        public static string DepthCharge {
            get {
                return ResourceManager.GetString("DepthCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyer.
        /// </summary>
        public static string Destroyer {
            get {
                return ResourceManager.GetString("Destroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ship.
        /// </summary>
        public static string DispersionGraphWindow_AddShip {
            get {
                return ResourceManager.GetString("DispersionGraphWindow_AddShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ship.
        /// </summary>
        public static string DispersionGraphWindow_RemoveShip {
            get {
                return ResourceManager.GetString("DispersionGraphWindow_RemoveShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispersion visualization.
        /// </summary>
        public static string DispersionWindow_Title {
            get {
                return ResourceManager.GetString("DispersionWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string DownloadWindow_Percentage {
            get {
                return ResourceManager.GetString("DownloadWindow_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status :.
        /// </summary>
        public static string DownloadWindow_Status {
            get {
                return ResourceManager.GetString("DownloadWindow_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string DownloadWindow_StatusText {
            get {
                return ResourceManager.GetString("DownloadWindow_StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string Europe {
            get {
                return ResourceManager.GetString("Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference angle used start at 0° on the front (top of the image) and goes in a clockwise direction.
        /// </summary>
        public static string FiringAngleWindow_AngleExplanation {
            get {
                return ResourceManager.GetString("FiringAngleWindow_AngleExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some turret orientation is wrong. The data from WG doesn&apos;t include it, so we use a workaround that work for most cases. If you find a case of a turret orientation and/or angle being wrong, report it on Github or by joining the Discord server below..
        /// </summary>
        public static string FiringAngleWindow_Disclaimer {
            get {
                return ResourceManager.GetString("FiringAngleWindow_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold all angles.
        /// </summary>
        public static string FiringAngleWindow_HideAll {
            get {
                return ResourceManager.GetString("FiringAngleWindow_HideAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never show angles.
        /// </summary>
        public static string FiringAngleWindow_PermaTextOff {
            get {
                return ResourceManager.GetString("FiringAngleWindow_PermaTextOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show angles.
        /// </summary>
        public static string FiringAngleWindow_PermaTextOn {
            get {
                return ResourceManager.GetString("FiringAngleWindow_PermaTextOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all angles.
        /// </summary>
        public static string FiringAngleWindow_ShowAll {
            get {
                return ResourceManager.GetString("FiringAngleWindow_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum range for the warning to appear.
        /// </summary>
        public static string IncomingFireAlertDesc {
            get {
                return ResourceManager.GetString("IncomingFireAlertDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        public static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to menu.
        /// </summary>
        public static string MainWindow_BackToMenu {
            get {
                return ResourceManager.GetString("MainWindow_BackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base XP.
        /// </summary>
        public static string MainWindow_BaseXp {
            get {
                return ResourceManager.GetString("MainWindow_BaseXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Skills and Camo.
        /// </summary>
        public static string MainWindow_CaptainSkills {
            get {
                return ResourceManager.GetString("MainWindow_CaptainSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander XP :.
        /// </summary>
        public static string MainWindow_CommanderXp {
            get {
                return ResourceManager.GetString("MainWindow_CommanderXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander XP bonus %.
        /// </summary>
        public static string MainWindow_CommanderXpBonus {
            get {
                return ResourceManager.GetString("MainWindow_CommanderXpBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free XP :.
        /// </summary>
        public static string MainWindow_FreeXp {
            get {
                return ResourceManager.GetString("MainWindow_FreeXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free XP Bonus %.
        /// </summary>
        public static string MainWindow_FreeXpBonus {
            get {
                return ResourceManager.GetString("MainWindow_FreeXpBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new ship.
        /// </summary>
        public static string MainWindow_NewShipSelection {
            get {
                return ResourceManager.GetString("MainWindow_NewShipSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Build.
        /// </summary>
        public static string MainWindow_ResetBuild {
            get {
                return ResourceManager.GetString("MainWindow_ResetBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Build.
        /// </summary>
        public static string MainWindow_ShareBuild {
            get {
                return ResourceManager.GetString("MainWindow_ShareBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals.
        /// </summary>
        public static string MainWindow_Signals {
            get {
                return ResourceManager.GetString("MainWindow_Signals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final XP :.
        /// </summary>
        public static string MainWindow_Xp {
            get {
                return ResourceManager.GetString("MainWindow_Xp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP bonus %.
        /// </summary>
        public static string MainWindow_XpBonus {
            get {
                return ResourceManager.GetString("MainWindow_XpBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP Calculator.
        /// </summary>
        public static string MainWindow_XpCalculator {
            get {
                return ResourceManager.GetString("MainWindow_XpCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected ship has already been added.
        /// </summary>
        public static string MessageBox_DuplicateShip {
            get {
                return ResourceManager.GetString("MessageBox_DuplicateShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBox_Error {
            get {
                return ResourceManager.GetString("MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected ship has no main guns.
        /// </summary>
        public static string MessageBox_ShipNoGun {
            get {
                return ResourceManager.GetString("MessageBox_ShipNoGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        public static string Netherlands {
            get {
                return ResourceManager.GetString("Netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan America.
        /// </summary>
        public static string PanAmerica {
            get {
                return ResourceManager.GetString("PanAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan Asia.
        /// </summary>
        public static string PanAsia {
            get {
                return ResourceManager.GetString("PanAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocket.
        /// </summary>
        public static string Rocket {
            get {
                return ResourceManager.GetString("Rocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        public static string Russia {
            get {
                return ResourceManager.GetString("Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art by :.
        /// </summary>
        public static string SettingsWindow_ArtBy {
            get {
                return ResourceManager.GetString("SettingsWindow_ArtBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic updates.
        /// </summary>
        public static string SettingsWindow_AutoUpdate {
            get {
                return ResourceManager.GetString("SettingsWindow_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsWindow_Cancel {
            get {
                return ResourceManager.GetString("SettingsWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string SettingsWindow_Clean {
            get {
                return ResourceManager.GetString("SettingsWindow_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean stored application data.
        /// </summary>
        public static string SettingsWindow_CleanAppData {
            get {
                return ResourceManager.GetString("SettingsWindow_CleanAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable custom path.
        /// </summary>
        public static string SettingsWindow_CustomPath {
            get {
                return ResourceManager.GetString("SettingsWindow_CustomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Conversion :.
        /// </summary>
        public static string SettingsWindow_Data {
            get {
                return ResourceManager.GetString("SettingsWindow_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by :.
        /// </summary>
        public static string SettingsWindow_DevelopedBy {
            get {
                return ResourceManager.GetString("SettingsWindow_DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devs: .
        /// </summary>
        public static string SettingsWindow_Devs {
            get {
                return ResourceManager.GetString("SettingsWindow_Devs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string SettingsWindow_Info {
            get {
                return ResourceManager.GetString("SettingsWindow_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert custom path.
        /// </summary>
        public static string SettingsWindow_InsertCustomPath {
            get {
                return ResourceManager.GetString("SettingsWindow_InsertCustomPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsWindow_Language {
            get {
                return ResourceManager.GetString("SettingsWindow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Devs:.
        /// </summary>
        public static string SettingsWindow_LeadDevs {
            get {
                return ResourceManager.GetString("SettingsWindow_LeadDevs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string SettingsWindow_Reset {
            get {
                return ResourceManager.GetString("SettingsWindow_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings to default.
        /// </summary>
        public static string SettingsWindow_ResetSettings {
            get {
                return ResourceManager.GetString("SettingsWindow_ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsWindow_Save {
            get {
                return ResourceManager.GetString("SettingsWindow_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Exit.
        /// </summary>
        public static string SettingsWindow_SaveExit {
            get {
                return ResourceManager.GetString("SettingsWindow_SaveExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string SettingsWindow_Server {
            get {
                return ResourceManager.GetString("SettingsWindow_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindow_Settings {
            get {
                return ResourceManager.GetString("SettingsWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string SettingsWindow_Version {
            get {
                return ResourceManager.GetString("SettingsWindow_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ShipSelectionWindow_ClassFilter {
            get {
                return ResourceManager.GetString("ShipSelectionWindow_ClassFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ShipSelectionWindow_ConfirmButton {
            get {
                return ResourceManager.GetString("ShipSelectionWindow_ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation.
        /// </summary>
        public static string ShipSelectionWindow_NationFilter {
            get {
                return ResourceManager.GetString("ShipSelectionWindow_NationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ships matching the filtering criteria found.
        /// </summary>
        public static string ShipSelectionWindow_NoResultsFound {
            get {
                return ResourceManager.GetString("ShipSelectionWindow_NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Ship.
        /// </summary>
        public static string ShipSelectionWindow_SearchShip {
            get {
                return ResourceManager.GetString("ShipSelectionWindow_SearchShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier.
        /// </summary>
        public static string ShipSelectionWindow_TierFilter {
            get {
                return ResourceManager.GetString("ShipSelectionWindow_TierFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ShipSelectionWindow_TypeFilter {
            get {
                return ResourceManager.GetString("ShipSelectionWindow_TypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA Defense.
        /// </summary>
        public static string ShipStats_AADefense {
            get {
                return ResourceManager.GetString("ShipStats_AADefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aiming rate change while moving during preparation.
        /// </summary>
        public static string ShipStats_AimingPreparationRateMoving {
            get {
                return ResourceManager.GetString("ShipStats_AimingPreparationRateMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aiming rate change while moving during aiming.
        /// </summary>
        public static string ShipStats_AimingRateMoving {
            get {
                return ResourceManager.GetString("ShipStats_AimingRateMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aiming time.
        /// </summary>
        public static string ShipStats_AimingTime {
            get {
                return ResourceManager.GetString("ShipStats_AimingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircrafts.
        /// </summary>
        public static string ShipStats_Aircraft {
            get {
                return ResourceManager.GetString("ShipStats_Aircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft HP.
        /// </summary>
        public static string ShipStats_AircraftHP {
            get {
                return ResourceManager.GetString("ShipStats_AircraftHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airstrike.
        /// </summary>
        public static string ShipStats_Airstrike {
            get {
                return ResourceManager.GetString("ShipStats_Airstrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons per plane.
        /// </summary>
        public static string ShipStats_AmmoPerAttack {
            get {
                return ResourceManager.GetString("ShipStats_AmmoPerAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arming distance.
        /// </summary>
        public static string ShipStats_ArmingDistance {
            get {
                return ResourceManager.GetString("ShipStats_ArmingDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arming Threshold.
        /// </summary>
        public static string ShipStats_ArmingThreshold {
            get {
                return ResourceManager.GetString("ShipStats_ArmingThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arming Treshold.
        /// </summary>
        public static string ShipStats_ArmingTreshold {
            get {
                return ResourceManager.GetString("ShipStats_ArmingTreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASW Airstrike.
        /// </summary>
        public static string ShipStats_AswAirstrike {
            get {
                return ResourceManager.GetString("ShipStats_AswAirstrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack cooldown.
        /// </summary>
        public static string ShipStats_AttackCd {
            get {
                return ResourceManager.GetString("ShipStats_AttackCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Flights.
        /// </summary>
        public static string ShipStats_AvailableFlights {
            get {
                return ResourceManager.GetString("ShipStats_AvailableFlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bombs per plane.
        /// </summary>
        public static string ShipStats_BombsPerPlane {
            get {
                return ResourceManager.GetString("ShipStats_BombsPerPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb Type.
        /// </summary>
        public static string ShipStats_BombType {
            get {
                return ResourceManager.GetString("ShipStats_BombType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bombs in Payload.
        /// </summary>
        public static string ShipStats_BompPayload {
            get {
                return ResourceManager.GetString("ShipStats_BompPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artillery Burst mode.
        /// </summary>
        public static string ShipStats_BurstMode {
            get {
                return ResourceManager.GetString("ShipStats_BurstMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can hit.
        /// </summary>
        public static string ShipStats_CanHitClasses {
            get {
                return ResourceManager.GetString("ShipStats_CanHitClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concealment.
        /// </summary>
        public static string ShipStats_Concealment {
            get {
                return ResourceManager.GetString("ShipStats_Concealment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concealment by air.
        /// </summary>
        public static string ShipStats_ConcealmentByAir {
            get {
                return ResourceManager.GetString("ShipStats_ConcealmentByAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When on fire.
        /// </summary>
        public static string ShipStats_ConcealmentByAirFire {
            get {
                return ResourceManager.GetString("ShipStats_ConcealmentByAirFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concealment by sea.
        /// </summary>
        public static string ShipStats_ConcealmentBySea {
            get {
                return ResourceManager.GetString("ShipStats_ConcealmentBySea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When on fire.
        /// </summary>
        public static string ShipStats_ConcealmentBySeaFire {
            get {
                return ResourceManager.GetString("ShipStats_ConcealmentBySeaFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After firing in smoke.
        /// </summary>
        public static string ShipStats_ConcealmentBySeaFiringSmoke {
            get {
                return ResourceManager.GetString("ShipStats_ConcealmentBySeaFiringSmoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant Damage.
        /// </summary>
        public static string ShipStats_ConstantDamage {
            get {
                return ResourceManager.GetString("ShipStats_ConstantDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooldown.
        /// </summary>
        public static string ShipStats_Cooldown {
            get {
                return ResourceManager.GetString("ShipStats_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruising speed.
        /// </summary>
        public static string ShipStats_CruisingSpeed {
            get {
                return ResourceManager.GetString("ShipStats_CruisingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string ShipStats_Damage {
            get {
                return ResourceManager.GetString("ShipStats_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage taken during attack.
        /// </summary>
        public static string ShipStats_DamageTakenDuringAttack {
            get {
                return ResourceManager.GetString("ShipStats_DamageTakenDuringAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string ShipStats_Delay {
            get {
                return ResourceManager.GetString("ShipStats_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASW Depth Charges.
        /// </summary>
        public static string ShipStats_DepthChargesLauncher {
            get {
                return ResourceManager.GetString("ShipStats_DepthChargesLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth Explosion Radius.
        /// </summary>
        public static string ShipStats_DepthExplosion {
            get {
                return ResourceManager.GetString("ShipStats_DepthExplosion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detectability range.
        /// </summary>
        public static string ShipStats_Detectability {
            get {
                return ResourceManager.GetString("ShipStats_Detectability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop time.
        /// </summary>
        public static string ShipStats_DropTime {
            get {
                return ResourceManager.GetString("ShipStats_DropTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string ShipStats_Duration {
            get {
                return ResourceManager.GetString("ShipStats_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max fires.
        /// </summary>
        public static string ShipStats_FireAmount {
            get {
                return ResourceManager.GetString("ShipStats_FireAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Chance.
        /// </summary>
        public static string ShipStats_FireChance {
            get {
                return ResourceManager.GetString("ShipStats_FireChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total damage per fire.
        /// </summary>
        public static string ShipStats_FireDamageTotal {
            get {
                return ResourceManager.GetString("ShipStats_FireDamageTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS per fire.
        /// </summary>
        public static string ShipStats_FireDPS {
            get {
                return ResourceManager.GetString("ShipStats_FireDPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Duration.
        /// </summary>
        public static string ShipStats_FireDuration {
            get {
                return ResourceManager.GetString("ShipStats_FireDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire chance reduction.
        /// </summary>
        public static string ShipStats_FireReduction {
            get {
                return ResourceManager.GetString("ShipStats_FireReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total fire damage.
        /// </summary>
        public static string ShipStats_FireTotalDamage {
            get {
                return ResourceManager.GetString("ShipStats_FireTotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Ping duration.
        /// </summary>
        public static string ShipStats_FirstPingDuration {
            get {
                return ResourceManager.GetString("ShipStats_FirstPingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flak.
        /// </summary>
        public static string ShipStats_Flak {
            get {
                return ResourceManager.GetString("ShipStats_Flak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flak Damage.
        /// </summary>
        public static string ShipStats_FlakDamage {
            get {
                return ResourceManager.GetString("ShipStats_FlakDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max floods.
        /// </summary>
        public static string ShipStats_FloodAmount {
            get {
                return ResourceManager.GetString("ShipStats_FloodAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total damage per flood.
        /// </summary>
        public static string ShipStats_FloodDamageTotal {
            get {
                return ResourceManager.GetString("ShipStats_FloodDamageTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS per flooding.
        /// </summary>
        public static string ShipStats_FloodDPS {
            get {
                return ResourceManager.GetString("ShipStats_FloodDPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flooding duration.
        /// </summary>
        public static string ShipStats_FloodDuration {
            get {
                return ResourceManager.GetString("ShipStats_FloodDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flooding Chance.
        /// </summary>
        public static string ShipStats_FloodingChance {
            get {
                return ResourceManager.GetString("ShipStats_FloodingChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flooding probability.
        /// </summary>
        public static string ShipStats_FloodProbability {
            get {
                return ResourceManager.GetString("ShipStats_FloodProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo protection.
        /// </summary>
        public static string ShipStats_FloodTorpedoProtection {
            get {
                return ResourceManager.GetString("ShipStats_FloodTorpedoProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total flood damage.
        /// </summary>
        public static string ShipStats_FloodTotalDamage {
            get {
                return ResourceManager.GetString("ShipStats_FloodTotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to arrive.
        /// </summary>
        public static string ShipStats_FlyAwayTime {
            get {
                return ResourceManager.GetString("ShipStats_FlyAwayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuse Timer.
        /// </summary>
        public static string ShipStats_FuseTimer {
            get {
                return ResourceManager.GetString("ShipStats_FuseTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Chance.
        /// </summary>
        public static string ShipStats_HitChance {
            get {
                return ResourceManager.GetString("ShipStats_HitChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Points.
        /// </summary>
        public static string ShipStats_HitPoints {
            get {
                return ResourceManager.GetString("ShipStats_HitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Dispersion.
        /// </summary>
        public static string ShipStats_HorizontalDisp {
            get {
                return ResourceManager.GetString("ShipStats_HorizontalDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb in inner ellipse.
        /// </summary>
        public static string ShipStats_InnerBombPercentage {
            get {
                return ResourceManager.GetString("ShipStats_InnerBombPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial boost duration.
        /// </summary>
        public static string ShipStats_JatoDuration {
            get {
                return ResourceManager.GetString("ShipStats_JatoDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial boost speed multiplier.
        /// </summary>
        public static string ShipStats_JatoSpeedMultiplier {
            get {
                return ResourceManager.GetString("ShipStats_JatoSpeedMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Range Aura.
        /// </summary>
        public static string ShipStats_LongAura {
            get {
                return ResourceManager.GetString("ShipStats_LongAura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Range Aura.
        /// </summary>
        public static string ShipStats_LongRangeAA {
            get {
                return ResourceManager.GetString("ShipStats_LongRangeAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Battery.
        /// </summary>
        public static string ShipStats_MainBattery {
            get {
                return ResourceManager.GetString("ShipStats_MainBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maneuverability.
        /// </summary>
        public static string ShipStats_Maneuverability {
            get {
                return ResourceManager.GetString("ShipStats_Maneuverability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full power backward time.
        /// </summary>
        public static string ShipStats_ManeuverabilityFullPowerBackward {
            get {
                return ResourceManager.GetString("ShipStats_ManeuverabilityFullPowerBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full power forward time.
        /// </summary>
        public static string ShipStats_ManeuverabilityFullPowerForward {
            get {
                return ResourceManager.GetString("ShipStats_ManeuverabilityFullPowerForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max speed.
        /// </summary>
        public static string ShipStats_ManeuverabilityMaxSpeed {
            get {
                return ResourceManager.GetString("ShipStats_ManeuverabilityMaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rudder shift time.
        /// </summary>
        public static string ShipStats_ManeuverabilityRudderShiftTime {
            get {
                return ResourceManager.GetString("ShipStats_ManeuverabilityRudderShiftTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning circle.
        /// </summary>
        public static string ShipStats_ManeuverabilityTurningCircle {
            get {
                return ResourceManager.GetString("ShipStats_ManeuverabilityTurningCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of fires.
        /// </summary>
        public static string ShipStats_MaxFireAmount {
            get {
                return ResourceManager.GetString("ShipStats_MaxFireAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of floodings.
        /// </summary>
        public static string ShipStats_MaxFloodAmount {
            get {
                return ResourceManager.GetString("ShipStats_MaxFloodAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum range.
        /// </summary>
        public static string ShipStats_MaximumDistance {
            get {
                return ResourceManager.GetString("ShipStats_MaximumDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max drop lenght.
        /// </summary>
        public static string ShipStats_MaximumFlightDistance {
            get {
                return ResourceManager.GetString("ShipStats_MaximumFlightDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max planes on deck.
        /// </summary>
        public static string ShipStats_MaxNumberOnDeck {
            get {
                return ResourceManager.GetString("ShipStats_MaxNumberOnDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max speed.
        /// </summary>
        public static string ShipStats_MaxSpeed {
            get {
                return ResourceManager.GetString("ShipStats_MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Range Aura.
        /// </summary>
        public static string ShipStats_MediumAura {
            get {
                return ResourceManager.GetString("ShipStats_MediumAura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Range Aura.
        /// </summary>
        public static string ShipStats_MediumRangeAA {
            get {
                return ResourceManager.GetString("ShipStats_MediumRangeAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum range.
        /// </summary>
        public static string ShipStats_MinimumDistance {
            get {
                return ResourceManager.GetString("ShipStats_MinimumDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min speed.
        /// </summary>
        public static string ShipStats_MinSpeed {
            get {
                return ResourceManager.GetString("ShipStats_MinSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ShipStats_Name {
            get {
                return ResourceManager.GetString("ShipStats_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft per attack.
        /// </summary>
        public static string ShipStats_NumberDuringAttack {
            get {
                return ResourceManager.GetString("ShipStats_NumberDuringAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft in a squadron.
        /// </summary>
        public static string ShipStats_NumberInSquad {
            get {
                return ResourceManager.GetString("ShipStats_NumberInSquad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        public static string ShipStats_NumberOfUses {
            get {
                return ResourceManager.GetString("ShipStats_NumberOfUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overmatch capability.
        /// </summary>
        public static string ShipStats_Overmatch {
            get {
                return ResourceManager.GetString("ShipStats_Overmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penetration.
        /// </summary>
        public static string ShipStats_Penetration {
            get {
                return ResourceManager.GetString("ShipStats_Penetration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Duration.
        /// </summary>
        public static string ShipStats_PingDuration {
            get {
                return ResourceManager.GetString("ShipStats_PingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinger gun.
        /// </summary>
        public static string ShipStats_PingerGun {
            get {
                return ResourceManager.GetString("ShipStats_PingerGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Speed.
        /// </summary>
        public static string ShipStats_PingSpeed {
            get {
                return ResourceManager.GetString("ShipStats_PingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping width.
        /// </summary>
        public static string ShipStats_PingWidth {
            get {
                return ResourceManager.GetString("ShipStats_PingWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hp per plane.
        /// </summary>
        public static string ShipStats_PlaneHP {
            get {
                return ResourceManager.GetString("ShipStats_PlaneHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post attack invulnerability time.
        /// </summary>
        public static string ShipStats_PostAttackInvulnerabilityDuration {
            get {
                return ResourceManager.GetString("ShipStats_PostAttackInvulnerabilityDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation time.
        /// </summary>
        public static string ShipStats_PreparationTime {
            get {
                return ResourceManager.GetString("ShipStats_PreparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string ShipStats_Range {
            get {
                return ResourceManager.GetString("ShipStats_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaction Time.
        /// </summary>
        public static string ShipStats_ReactionTime {
            get {
                return ResourceManager.GetString("ShipStats_ReactionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Time.
        /// </summary>
        public static string ShipStats_Reload {
            get {
                return ResourceManager.GetString("ShipStats_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload after burst.
        /// </summary>
        public static string ShipStats_ReloadAfterBurst {
            get {
                return ResourceManager.GetString("ShipStats_ReloadAfterBurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload during burst.
        /// </summary>
        public static string ShipStats_ReloadDuringBurst {
            get {
                return ResourceManager.GetString("ShipStats_ReloadDuringBurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits required.
        /// </summary>
        public static string ShipStats_RequiredHits {
            get {
                return ResourceManager.GetString("ShipStats_RequiredHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration time.
        /// </summary>
        public static string ShipStats_RestorationTime {
            get {
                return ResourceManager.GetString("ShipStats_RestorationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricochet Angles.
        /// </summary>
        public static string ShipStats_RicochetAngles {
            get {
                return ResourceManager.GetString("ShipStats_RicochetAngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate of fire.
        /// </summary>
        public static string ShipStats_RoF {
            get {
                return ResourceManager.GetString("ShipStats_RoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Ping duration.
        /// </summary>
        public static string ShipStats_SecondPingDuration {
            get {
                return ResourceManager.GetString("ShipStats_SecondPingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shells.
        /// </summary>
        public static string ShipStats_Shells {
            get {
                return ResourceManager.GetString("ShipStats_Shells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Shell Velocity.
        /// </summary>
        public static string ShipStats_ShellVelocity {
            get {
                return ResourceManager.GetString("ShipStats_ShellVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Weight.
        /// </summary>
        public static string ShipStats_ShellWeight {
            get {
                return ResourceManager.GetString("ShipStats_ShellWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Range Aura.
        /// </summary>
        public static string ShipStats_ShortAura {
            get {
                return ResourceManager.GetString("ShipStats_ShortAura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Range Aura.
        /// </summary>
        public static string ShipStats_ShortRangeAA {
            get {
                return ResourceManager.GetString("ShipStats_ShortRangeAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shots in one burst.
        /// </summary>
        public static string ShipStats_ShotInBurst {
            get {
                return ResourceManager.GetString("ShipStats_ShotInBurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma.
        /// </summary>
        public static string ShipStats_Sigma {
            get {
                return ResourceManager.GetString("ShipStats_Sigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special abilities.
        /// </summary>
        public static string ShipStats_SpecialAbility {
            get {
                return ResourceManager.GetString("ShipStats_SpecialAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string ShipStats_Speed {
            get {
                return ResourceManager.GetString("ShipStats_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting planes on deck.
        /// </summary>
        public static string ShipStats_StartingNumberOnDeck {
            get {
                return ResourceManager.GetString("ShipStats_StartingNumberOnDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivability.
        /// </summary>
        public static string ShipStats_Survivability {
            get {
                return ResourceManager.GetString("ShipStats_Survivability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theoretical DPM.
        /// </summary>
        public static string ShipStats_TheoreticalDPM {
            get {
                return ResourceManager.GetString("ShipStats_TheoreticalDPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to fully aimed.
        /// </summary>
        public static string ShipStats_TimeToFullyAimed {
            get {
                return ResourceManager.GetString("ShipStats_TimeToFullyAimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to switch ammo.
        /// </summary>
        public static string ShipStats_TimeToSwitch {
            get {
                return ResourceManager.GetString("ShipStats_TimeToSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo.
        /// </summary>
        public static string ShipStats_Torpedo {
            get {
                return ResourceManager.GetString("ShipStats_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo Area.
        /// </summary>
        public static string ShipStats_TorpedoArea {
            get {
                return ResourceManager.GetString("ShipStats_TorpedoArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo Launchers.
        /// </summary>
        public static string ShipStats_TorpedoLaunchers {
            get {
                return ResourceManager.GetString("ShipStats_TorpedoLaunchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo protection.
        /// </summary>
        public static string ShipStats_TorpedoProtection {
            get {
                return ResourceManager.GetString("ShipStats_TorpedoProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traverse speed.
        /// </summary>
        public static string ShipStats_TraverseSpeed {
            get {
                return ResourceManager.GetString("ShipStats_TraverseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180° turn time.
        /// </summary>
        public static string ShipStats_TurnTime {
            get {
                return ResourceManager.GetString("ShipStats_TurnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show turret angles.
        /// </summary>
        public static string ShipStats_TurretAngles {
            get {
                return ResourceManager.GetString("ShipStats_TurretAngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ShipStats_Type {
            get {
                return ResourceManager.GetString("ShipStats_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Dispersion.
        /// </summary>
        public static string ShipStats_VerticalDisp {
            get {
                return ResourceManager.GetString("ShipStats_VerticalDisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Type.
        /// </summary>
        public static string ShipStats_WeaponType {
            get {
                return ResourceManager.GetString("ShipStats_WeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action time.
        /// </summary>
        public static string ShipStats_WorkTime {
            get {
                return ResourceManager.GetString("ShipStats_WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags .
        /// </summary>
        public static string SignalSelector_Flags {
            get {
                return ResourceManager.GetString("SignalSelector_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Bomb.
        /// </summary>
        public static string SkipBomb {
            get {
                return ResourceManager.GetString("SkipBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        public static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Camo Images.
        /// </summary>
        public static string SplashScreen_CamoImages {
            get {
                return ResourceManager.GetString("SplashScreen_CamoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string SplashScreen_Done {
            get {
                return ResourceManager.GetString("SplashScreen_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Data.
        /// </summary>
        public static string SplashScreen_Json {
            get {
                return ResourceManager.GetString("SplashScreen_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Ship Images.
        /// </summary>
        public static string SplashScreen_ShipImages {
            get {
                return ResourceManager.GetString("SplashScreen_ShipImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error suring the loading of the build.
        /// </summary>
        public static string StartMenu_BuildLoadingError {
            get {
                return ResourceManager.GetString("StartMenu_BuildLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete build.
        /// </summary>
        public static string StartMenu_DeleteBuild {
            get {
                return ResourceManager.GetString("StartMenu_DeleteBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import build....
        /// </summary>
        public static string StartMenu_ImportBuild {
            get {
                return ResourceManager.GetString("StartMenu_ImportBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a build.
        /// </summary>
        public static string StartMenu_LoadBuild {
            get {
                return ResourceManager.GetString("StartMenu_LoadBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new build.
        /// </summary>
        public static string StartMenu_NewBuild {
            get {
                return ResourceManager.GetString("StartMenu_NewBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings and Info.
        /// </summary>
        public static string StartMenu_Settings {
            get {
                return ResourceManager.GetString("StartMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submarine.
        /// </summary>
        public static string Submarine {
            get {
                return ResourceManager.GetString("Submarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech Tree.
        /// </summary>
        public static string TechTree {
            get {
                return ResourceManager.GetString("TechTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Ship.
        /// </summary>
        public static string TestShip {
            get {
                return ResourceManager.GetString("TestShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Slot.
        /// </summary>
        public static string TITLE_PlaceholderMod {
            get {
                return ResourceManager.GetString("TITLE_PlaceholderMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo.
        /// </summary>
        public static string Torpedo {
            get {
                return ResourceManager.GetString("Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.K..
        /// </summary>
        public static string UnitedKingdom {
            get {
                return ResourceManager.GetString("UnitedKingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.S.A..
        /// </summary>
        public static string Usa {
            get {
                return ResourceManager.GetString("Usa", resourceCulture);
            }
        }
    }
}
