namespace WoWsShipBuilder.Data.Generator.Test.DataElementGeneratorTests;

public partial class DataElementGeneratorTest
{
    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextNoLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial class TestDataContainer : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ArgumentsCollectionName = nameof(TestValues))]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial class TestDataContainer
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.FormattedTextDataElement(this.Test, this.TestValues, global::WoWsShipBuilder.DataElements.DataElementTextKind.Plain, global::WoWsShipBuilder.DataElements.DataElementTextKind.Plain));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextValuesLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial class TestDataContainer : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ArgumentsCollectionName = nameof(TestValues), ArgumentsTextKind = TextKind.LocalizationKey)]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial class TestDataContainer
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.FormattedTextDataElement(this.Test, this.TestValues, global::WoWsShipBuilder.DataElements.DataElementTextKind.Plain, global::WoWsShipBuilder.DataElements.DataElementTextKind.LocalizationKey));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextKeyLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial class TestDataContainer : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ArgumentsCollectionName = nameof(TestValues), ValueTextKind = TextKind.LocalizationKey)]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial class TestDataContainer
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.FormattedTextDataElement(this.Test, this.TestValues, global::WoWsShipBuilder.DataElements.DataElementTextKind.LocalizationKey, global::WoWsShipBuilder.DataElements.DataElementTextKind.Plain));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextKeyAndValueLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial class TestDataContainer : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ArgumentsCollectionName = nameof(TestValues), ValueTextKind = TextKind.LocalizationKey, ArgumentsTextKind = TextKind.LocalizationKey)]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial class TestDataContainer
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.FormattedTextDataElement(this.Test, this.TestValues, global::WoWsShipBuilder.DataElements.DataElementTextKind.LocalizationKey, global::WoWsShipBuilder.DataElements.DataElementTextKind.LocalizationKey));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextValuesAppLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial class TestDataContainer : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ArgumentsCollectionName = nameof(TestValues), ArgumentsTextKind = TextKind.AppLocalizationKey)]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial class TestDataContainer
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.FormattedTextDataElement(this.Test, this.TestValues, global::WoWsShipBuilder.DataElements.DataElementTextKind.Plain, global::WoWsShipBuilder.DataElements.DataElementTextKind.AppLocalizationKey));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextKeyAppLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial class TestDataContainer : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ArgumentsCollectionName = nameof(TestValues), ValueTextKind = TextKind.AppLocalizationKey)]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial class TestDataContainer
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.FormattedTextDataElement(this.Test, this.TestValues, global::WoWsShipBuilder.DataElements.DataElementTextKind.AppLocalizationKey, global::WoWsShipBuilder.DataElements.DataElementTextKind.Plain));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    [Category("FormattedText")]
    public async Task GenerateCode_FormattedTextKeyAndValueAppLocalization_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial class TestDataContainer : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.FormattedText, ArgumentsCollectionName = nameof(TestValues), ValueTextKind = TextKind.AppLocalizationKey, ArgumentsTextKind = TextKind.AppLocalizationKey)]
                         public string Test { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial class TestDataContainer
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataContainerBase.ShouldAdd(this.Test))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.FormattedTextDataElement(this.Test, this.TestValues, global::WoWsShipBuilder.DataElements.DataElementTextKind.AppLocalizationKey, global::WoWsShipBuilder.DataElements.DataElementTextKind.AppLocalizationKey));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }
}
