namespace WoWsShipBuilder.Data.Generator.Test.DataElementGeneratorTests;

public partial class DataElementGeneratorTest
{
    [Test]
    public async Task GenerateCode_EmptyRecord_EmptyMethod()
    {
        var source = """
                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial record TestRecord : DataContainerBase
                     {
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial record TestRecord
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    public async Task GenerateCode_ElementWithCustomFilter_Success()
    {
        var source = """
                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial record TestRecord : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.KeyValueUnit, UnitKey = "FPM")]
                         [DataElementFiltering(true, nameof(this.ShouldDisplayTest))]
                         public decimal TestProperty { get; set; }

                         private bool ShouldDisplayTest(object obj)
                         {
                             return true;
                         }
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial record TestRecord
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (ShouldDisplayTest(this.TestProperty))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.KeyValueUnitDataElement("ShipStats_TestProperty", this.TestProperty.ToString(), "Unit_FPM"));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }

    [Test]
    public async Task GenerateCode_MixedElements_Success()
    {
        var source = """
                     using System.Collections.Generic;

                     using WoWsShipBuilder.DataElements.DataElementAttributes;
                     using WoWsShipBuilder.DataElements;

                     namespace Test;

                     [DataContainer]
                     public partial record TestRecord : DataContainerBase
                     {
                         [DataElementType(DataElementTypes.KeyValue, ValueTextKind = TextKind.LocalizationKey)]
                         public string Prop1 { get; set; } = default!;

                         [DataElementType(DataElementTypes.KeyValueUnit, UnitKey="Knots")]
                         public decimal Prop2 { get; set; } = default!;

                         [DataElementType(DataElementTypes.Tooltip, TooltipKey = "TestTooltip")]
                         public string Prop3 { get; set; } = default!;

                         [DataElementType(DataElementTypes.FormattedText, ArgumentsCollectionName = nameof(TestValues))]
                         public string Prop4 { get; set; } = default!;

                         public List<string> TestValues { get; set; } = new();
                     }
                     """;

        var expected = """
                       // <auto-generated />
                       #nullable enable
                       namespace Test
                       {
                           public partial record TestRecord
                           {
                               private void UpdateDataElements()
                               {
                                   this.DataElements.Clear();
                                   if (global::WoWsShipBuilder.DataElements.DataContainerBase.ShouldAdd(this.Prop1))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.KeyValueDataElement("ShipStats_Prop1", this.Prop1, global::WoWsShipBuilder.DataElements.DataElementTextKind.LocalizationKey));
                                   }

                                   if (global::WoWsShipBuilder.DataElements.DataContainerBase.ShouldAdd(this.Prop2))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.DataElements.KeyValueUnitDataElement("ShipStats_Prop2", this.Prop2.ToString(), "Unit_Knots"));
                                   }

                                   if (global::WoWsShipBuilder.DataElements.DataElements.DataContainerBase.ShouldAdd(this.Prop3))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.DataElements.TooltipDataElement("ShipStats_Prop3", this.Prop3, "ShipStats_TestTooltip", ""));
                                   }

                                   if (global::WoWsShipBuilder.DataElements.DataElements.DataContainerBase.ShouldAdd(this.Prop4))
                                   {
                                       this.DataElements.Add(new global::WoWsShipBuilder.DataElements.DataElements.FormattedTextDataElement(this.Prop4, this.TestValues, global::WoWsShipBuilder.DataElements.DataElements.DataElementTextKind.Plain, global::WoWsShipBuilder.DataElements.DataElements.DataElementTextKind.Plain));
                                   }
                               }
                           }
                       }

                       """;

        await CreateTest(source, expected).RunAsync();
    }
}
