name: Build and run tests on development branch

on:
  push:
    branches-ignore:
      - 'release/**'
      - 'l10n_development'
    paths-ignore:
      - '**/*.md'
      - '.github/*.png'
      - 'docs/**'
      - 'workflows/*.yml'
      - 'workflows/*.yaml'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '.github/*.png'
      - 'docs/**'
      - 'workflows/*.yml'
      - 'workflows/*.yaml'

jobs:
  build-test:
    name: Build application
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
      - name: Restore dependencies
        run: dotnet restore dirs.proj
      - name: Build application
        run: dotnet build dirs.proj --no-restore -c Release -p:TreatWarningsAsErrors=true
      - name: Test application
        run: dotnet test dirs.proj --no-build -c Release --verbosity normal
