name: Requirement check for merges with main.

on:
  pull_request:
    branches:
      - release/desktop

jobs:
  verify-velopack-release:
    runs-on: windows-latest
    name: Verify Velopack release process

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore dependencies
        run: dotnet restore dirs.proj
      - name: Build application
        run: dotnet build dirs.proj --no-restore -c Release
      - name: Test application
        run: dotnet test dirs.proj --no-build -c Release --verbosity normal

      - name: Extract certificate
        run: |
          $certB64 = '${{ secrets.WOWSSB_CERT }}'
          [IO.File]::WriteAllBytes("./wowssb.pfx", [Convert]::FromBase64String([char[]]$certB64))
      - name: Determine vpk version
        id: vpk-version
        run: echo ("VELOPACK_VERSION=" + (Select-Xml -Path ./src/WoWsShipBuilder.Desktop/WoWsShipBuilder.Desktop.csproj -XPath "//PackageReference[@Include='Velopack']" | Select-Object -ExpandProperty Node -First 1 | foreach {$_.Version})) >> $env:GITHUB_OUTPUT
      - name: Install vpk
        run: dotnet tool install -g --version ${{ steps.vpk-version.outputs.VELOPACK_VERSION }} vpk
      - name: Create Velopack Release
        run: |
          vpk download github -o artifacts/releases --repoUrl ${{ github.server_url }}/${{ github.repository }}
          build/BuildVelopackRelease.ps1 -skipBuild -signingCert wowssb.pfx -signingPassword '${{ secrets.WOWSSB_CERT_KEY }}'
        shell: pwsh
      - name: Cleanup certificate
        run: Remove-Item ./wowssb.pfx
