name: Build and run tests on development branch

on:
  push:
    branches:
      - development
    paths-ignore:
      - '**/*.md'
      - '.github/*.png'
      - 'docs/**/*.*'
      - 'workflows/*.yml'
      - 'deployment/**/*.*'
  pull_request:
    branches:
      - development
    paths-ignore:
      - '**/*.resx'
      - '**/*.md'
      - '.github/*.png'
      - 'docs/**/*.*'
      - 'workflows/*.yml'
      - 'deployment/**/*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    name: Build application on dev branch

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Restore dependencies
        run: dotnet restore
      - name: Build application
        run: dotnet build --no-restore -c Release -p:TreatWarningsAsErrors=true
      - name: Test application
        run: dotnet test --no-build -c Release --verbosity normal
