name: Web Docker Release Check

on:
  pull_request:
    branches:
      - 'release/web'

jobs:
  buildApp:
    runs-on: ubuntu-latest
    name: Verify image build

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json
      - uses: dotnet/nbgv@master
        with:
          setAllVars: true
          path: src/WoWsShipBuilder.Web
      - name: Build container image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          tags: ghcr.io/wows-builder-team/wowssb:${{ env.NBGV_NuGetPackageVersion }}
          file: src/WoWsShipBuilder.Web/Dockerfile
